[versions]
springboot = "3.4.2"
springDependencyManagement = "1.1.7"

[libraries]
mybatisBootStarter = {module="org.mybatis.spring.boot:mybatis-spring-boot-starter" ,version="3.0.4"}
freemarker = {module="org.freemarker:freemarker" ,version="2.3.34"}
dmDriver = {module="com.dameng:DmJdbcDriver18" ,version="8.1.2.192"}
mysqlDriver = {module="com.mysql:mysql-connector-j" ,version="8.2.0"}



[plugins]
springboot = { id = "org.springframework.boot", version.ref = "springboot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }